services:
    app:
        image: 'php:8.3-fpm'
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    nginx:
        image: 'nginx:alpine'
        container_name: laravel_nginx
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:5173'
        volumes:
            - '.:/var/www/html'
            - './.devcontainer/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: 'mysql:8.0'
        container_name: laravel_mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            MYSQL_USER: '${DB_USERNAME:-laravel_user}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: 'redis:alpine'
        container_name: laravel_redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
        driver: local
