FROM php:8.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libpng-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    supervisor \
    nginx \
    nodejs \
    npm \
    default-mysql-client \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd xml \
    && pecl install redis \
    && docker-php-ext-enable redis

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u 1000 -d /home/sail sail
RUN mkdir -p /home/sail/.composer && \
    chown -R sail:sail /home/sail

# Set working directory
WORKDIR /var/www/html

# Copy nginx configuration
RUN rm /etc/nginx/sites-enabled/default
COPY .devcontainer/nginx.conf /etc/nginx/sites-available/default
RUN ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Copy supervisor configuration
COPY .devcontainer/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Copy php configuration
COPY .devcontainer/php.ini /usr/local/etc/php/conf.d/99-custom.ini

# Install Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Change current user to sail
USER sail

EXPOSE 80 5173

# Start supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
